const response = {
    SERVER_ERROR:                   'Unexpected Server Error!',
    UPDATE_SUCCESS:                 'Successfully Updated!',
    USER_NOT_FOUND:                 'User not found.',
    WRONG_OLD_PASSWORD:             'Incorrect old password.',
    INVALID_REQUEST:                'Invalid Request!',
    PASSWORD_RESET_EMAIL:           'Password reset email sent.',
    USED_EMAIL:                     'This email is already in use.',
    SUCCESS_REGISTER:               'Successfully Registered.',
    INVALID_COMBINATION:            'Invaid Email and Password combination.',
    SUCCESS_LOGIN:                  'Successfully Logged In.',
    SUCCESS_LOGOUT:                 'Sucessfully logged out.',
    INACTIVATED_REQUEST:            'Inacvitated user request.',
    SUCCESS_FETCH:                  'Successfully fetched.',
    SUCCESS_CREATED:                'Successfully Created.',
    SUCCESS_REMOVED:                'Successfully Removed.',
    EMPTY_IDENTIFIER:               'Identifier is empty.',
    EMPTY_MAKE:                     'Make is empty.',
    EMPTY_MODEL:                    'Model is empty.',
    EMPTY_PRICE:                    'Price is empty.',
    EMPTY_YEAR:                     'Year is empty.',
    EMPTY_ID:                       'Id is empty.',
    EMPTY_USER_ID:                  'User Id is empty.',
    EMPTY_NOTE:                     'Note is empty.',
    EMPTY_IMAGES:                   'Images is empty.',
    EMPTY_EMAIL:                    'Email is empty.',
    INVALID_EMAIL:                  'Invalid Email.',
    ACCESS_REVOKE:                  'Access for this account has been revoked.',
    EMAIL_EXIST_ERROR:              `This email doesn't exist.`,
    EMPTY_PASSWORD:                 'Password is empty.',
    PASSWORD_LENGTH_ERROR:          'Password length must be at least 5.',
    EMPTY_OLDPASSWORD:              'Oldpassword is empty.',
    OLDPASSWORD_LENGTH_ERROR:       'Oldpassword length must be at least 5.',
    EMPTY_NEWPASSWORD:              'Newpassword is empty.',
    NEWPASSWORD_LENGTH_ERROR:       'Newpassword length must be at least 5.',
    EMPTY_USERNAME:                 'Username is empty.',
    WRONG_USER_TOKEN:               'Incorrect user token',
    MUST_LOGIN:                     'You must log in!',
    TOKEN_EXPIRE:                   'Token Expired!',
    EMPTY_ACTIVEPAGE:               'ActivePage is empty.',
    EMPTY_PLATINUM:                 'Platinum is empty.',
    EMPTY_PALLADIUM:                'Palladium is empty.',
    EMPTY_RHODIUM:                  'Rhodium is empty.',
    EMPTY_WEIGHT:                   'Weight is empty.',
    NOT_FLOAT:                      `doesn't float.`,
    CSV_HEADER_ERROR:               'Invalid Csv template format',
    SUCCESS_CSV_UPLOAD:             'Your converter list is being processed. You will receive an email when your upload is completed.',
    ERROR_Rate_UPLOAD:              'Cannot save Converter Pricing'
};

module.exports = {
    RES: response
}
